### ISSUE TITLE
v2.0 重构计划

### ISSUE THREAD

**Issue by Integ** [Integ/BachEditor#12]
- [ ] 使用 Browserify 做模块化
- [ ] 目录结构重构
- [ ] 使用 gulp 构建
- [ ] 上传图片提供配置地址
- [ ] 剥离 MIDI.js 成为一个附加功能

**Comment by str2code** [comment]
我还以为这个项目死了呢。。。

**Comment by Integ** [comment]
决定放弃对浏览器的支持，使用 electron 彻底重写。
